# Generated by Django 5.1.4 on 2025-01-02 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorinfo',
            old_name='baseSalary',
            new_name='consultationFee',
        ),
        migrations.RenameField(
            model_name='doctorinfo',
            old_name='status',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='doctorinfo',
            old_name='notes',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='doctorinfo',
            old_name='behaviouranalyst',
            new_name='doctorname',
        ),
        migrations.RenameField(
            model_name='doctorinfo',
            old_name='hiringManager',
            new_name='emailID',
        ),
        migrations.RenameField(
            model_name='doctorinfo',
            old_name='positionname',
            new_name='expertise',
        ),
        migrations.RemoveField(
            model_name='doctorinfo',
            name='closedDate',
        ),
        migrations.RemoveField(
            model_name='doctorinfo',
            name='openingDate',
        ),
        migrations.RemoveField(
            model_name='doctorinfo',
            name='recruitingManager',
        ),
    ]
