# Generated by Django 5.1.4 on 2025-01-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Remarks', models.CharField(max_length=255)),
                ('contact', models.IntegerField(null=True)),
                ('consultationFee', models.IntegerField(null=True)),
                ('emailID', models.CharField(max_length=255)),
            ],
        ),
    ]
