# Generated by Django 5.1.4 on 2025-01-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='positions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positionname', models.CharField(max_length=255)),
                ('recruitingManager', models.CharField(max_length=255)),
                ('hiringManager', models.CharField(max_length=255)),
                ('openingDate', models.DateField(null=True)),
                ('closedDate', models.DateField(null=True)),
                ('notes', models.CharField(max_length=500)),
                ('status', models.IntegerField(null=True)),
                ('department', models.CharField(max_length=500)),
                ('baseSalary', models.IntegerField(null=True)),
            ],
        ),
    ]
